version: "3.7"

networks:
  master:
    external: true

services:
  gitea:
    image: gitea/gitea:1.13.2
    container_name: gitea
    restart: always    
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - HTTP_PORT=3000
    networks:
      - master
    dns:
      - 192.168.0.110
    ports:
      - "3000:3000"
      - "2222:22"
    volumes:
      - ./data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.port=3000"
      - "traefik.http.routers.gitea.rule=Host(`gitea.localnet`)"
      - "traefik.http.routers.gitea.entrypoints=web"
      - "traefik.http.routers.gitea.service=gitea"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"

