version: "3.7"

# networks:
#   master:
#     external: true

services:

  mysql:
    image: mariadb:10.5.8
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: semaphore
      MYSQL_USER: semaphore
      MYSQL_PASSWORD: semaphore
    volumes:
     - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  semaphore:
    image: ansiblesemaphore/semaphore:v2.6.7
    hostname: semaphore
    container_name: semaphore
    restart: always
    ports:
      - "3000:3000"
    # networks:
    #   - master
    dns:
      - 192.168.0.110
    volumes:
      - ./semaphore:/data
    depends_on:
      - mysql
    environment:
      SEMAPHORE_DB_USER: semaphore
      SEMAPHORE_DB_PASS: semaphore
      SEMAPHORE_DB_HOST: mysql
      SEMAPHORE_DB_PORT: 3306
      SEMAPHORE_DB: semaphore
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
      SEMAPHORE_ADMIN_PASSWORD: password
      SEMAPHORE_ADMIN_NAME: admin
      SEMAPHORE_ADMIN_EMAIL: admin@localhost
      SEMAPHORE_ADMIN: admin
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.port=4000"
    #   - "traefik.http.routers.drone.rule=Host(`drone.localnet`)"
    #   - "traefik.http.routers.drone.entrypoints=web"
    #   - "traefik.http.routers.drone.service=drone"
    #   - "traefik.http.services.drone.loadbalancer.server.port=4000"





