version: "3.7"

networks:
  master:
    external: true

services:

  traefik:
    image: "traefik:v2.2.0"
    container_name: traefik
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    # extra_hosts:
    #   - "gitea.somsi:192.168.0.110"
    #   - "drone.somsi:192.168.0.110"
    networks:
      - master
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
